ARG NODE_VERSION=18.15-alpine3.17

FROM node:$NODE_VERSION as deps

USER root

WORKDIR /usr/src/app

COPY package*.json ./
COPY . .

RUN npm ci
RUN npm run build

FROM node:$NODE_VERSION as build

WORKDIR /usr/src/app

USER root

COPY --from=deps --chown=node:node /usr/src/app/node_modules ./node_modules/
COPY --from=deps --chown=node:node /usr/src/app/dist ./dist/

RUN npm i -g serve

EXPOSE 3000

CMD [ "serve", "-s", "dist" ]